name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the `main` branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      # Step 4: Build the MkDocs site
      - name: Build the site
        run: mkdocs build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to (it will create this branch if it doesn't exist)
          folder: site  # The folder containing the built MkDocs site
          token: ${{ secrets.DOCS_DEPLOY_TOKEN }}  # GitHub's token for authentication